# Generated by Django 4.1.2 on 2022-10-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clipboard',
            name='id',
        ),
        migrations.AlterField(
            model_name='clipboard',
            name='idd',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
