# Generated by Django 4.1.2 on 2022-10-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v', '0002_remove_clipboard_id_alter_clipboard_idd'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clipboard',
            name='topic',
            field=models.TextField(null=True),
        ),
    ]
