# Generated by Django 3.2.13 on 2023-07-16 16:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v', '0007_alter_clipboard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='field',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
