# Generated by Django 3.2.13 on 2023-07-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v', '0008_clipboard_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clipboard',
            old_name='text',
            new_name='description',
        ),
    ]
